version: '3.8'
services:
  movies:
    image: prasanthmadullapalle/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: prasanthmadullapalle/paytmrecharge:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: prasanthmadullapalle/paytmtrain:latest
    ports:
      - "83:80"
    deploy:
      replicas: 6
  dth:
    image: prasanthmadullapalle/paytmdth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
